# Simplified provider configuration
# Only contains default models for each provider
providers:
  anthropic:
    default_model: "claude-3-5-sonnet-20241022"
  
  google:
    default_model: "gemini-1.5-flash"
  
  openai:
    default_model: "gpt-4o-mini"
  
  deepseek:
    default_model: "deepseek-chat"
  
  cerebras:
    default_model: "llama3.1-8b"
  
  groq:
    default_model: "llama-3.1-8b-instant"
  
  ollama:
    default_model: "llama3.1:8b"
