[project]
name = "transcripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=0.2.2",
    "langchain-openai==0.2.11",
    "langchain-text-splitters==0.3.2",
    "python-dotenv==1.0.1",
    "ratelimit>=2.2.1",
    "ratelimiter>=1.2.0.post0",
    "tweepy>=4.14.0",
    "youtube-transcript-api==0.6.3",
]
